import { type Lang } from "../i18n";
import raw from "../data/higher-mind-skills.json";

/**
 * Catalogue behind the Skills tab on /claude. The data file is generated by the public
 * repository's exporter (`bin/pg-export-public.py` -> `skills.json`) and copied here as a
 * snapshot, so the page never hand-writes a description that could drift from the repo.
 * Refresh: download `skills.json` from the repository's main branch into src/data/.
 */

export type Skill = {
  name: string;
  category: string;
  summary: string;
  description: string;
  path: string;
  plugin: boolean;
};

export type Agent = {
  name: string;
  model: string;
  tools: string;
  summary: string;
  path: string;
};

type Catalog = {
  schema_version: number;
  count: number;
  skills: Skill[];
  agents_count: number;
  agents: Agent[];
  install: { plugin: string; full_pg: string };
};

export const REPO_URL = "https://github.com/kamiljan11/coding-higher-mind";
export const SUPPORTED_SCHEMA = 1;

/** Display order and labels; the exporter writes the Polish key without diacritics. */
const CATEGORIES: { key: string; label: Record<Lang, string> }[] = [
  {
    key: "Architektura i decyzje",
    label: { en: "Architecture and decisions", pl: "Architektura i decyzje" },
  },
  { key: "Review i jakosc", label: { en: "Review and quality", pl: "Review i jakość" } },
  { key: "Debug", label: { en: "Debugging", pl: "Debugowanie" } },
  { key: "Petle agentow", label: { en: "Agent loops", pl: "Pętle agentów" } },
  { key: "Frontend", label: { en: "Frontend", pl: "Frontend" } },
  { key: "Pisanie", label: { en: "Writing", pl: "Pisanie" } },
];

const OTHER: Record<Lang, string> = { en: "Other", pl: "Inne" };

export function categoryLabel(key: string, lang: Lang): string {
  return CATEGORIES.find((c) => c.key === key)?.label[lang] ?? OTHER[lang];
}

/** Groups skills in the fixed category order; unknown categories land in "Other" at the end, never vanish. */
export function groupSkills(skills: Skill[], lang: Lang): { label: string; skills: Skill[] }[] {
  const known = CATEGORIES.map((c) => ({
    label: c.label[lang],
    skills: skills.filter((s) => s.category === c.key),
  }));
  const rest = skills.filter((s) => !CATEGORIES.some((c) => c.key === s.category));
  return [...known, { label: OTHER[lang], skills: rest }].filter((g) => g.skills.length > 0);
}

export function repoFileUrl(path: string): string {
  return `${REPO_URL}/tree/main/${path}`;
}

/** Fails loudly at build time if the exporter changes the shape the page renders. */
export function loadCatalog(data: unknown = raw): Catalog {
  const c = data as Catalog;
  if (
    c.schema_version !== SUPPORTED_SCHEMA ||
    !Array.isArray(c.skills) ||
    !Array.isArray(c.agents)
  ) {
    throw new Error(
      `higher-mind-skills.json: unsupported schema ${String(c.schema_version)} (expected ${SUPPORTED_SCHEMA})`,
    );
  }
  return c;
}
