"""Render the book PDFs in public/books/ to WebP pages for the /ksiazki flipbook.

Run from the repo root after a PDF changes, then commit the output:

    python scripts/render-book-pages.py

Writes public/books/pages/<book>/p-001.webp ... and src/data/bookPages.ts with the page counts
and page size. See docs/adr/0005-book-flipbook-with-prerendered-pages.md.
"""

import io
import json
import pathlib
import shutil

import fitz  # PyMuPDF
from PIL import Image

ROOT = pathlib.Path(__file__).resolve().parent.parent
BOOKS = {
    "short": "public/books/Simplified-Practical-Spirituality-Short.pdf",
    "full": "public/books/Simplified-Practical-Spirituality.pdf",
}
SCALE = 1.6
QUALITY = 74


def render(key: str, pdf: str) -> dict[str, int]:
    out = ROOT / "public" / "books" / "pages" / key
    if out.exists():
        shutil.rmtree(out)
    out.mkdir(parents=True)
    doc = fitz.open(ROOT / pdf)
    width = height = 0
    for i in range(1, doc.page_count + 1):
        pix = doc.load_page(i - 1).get_pixmap(matrix=fitz.Matrix(SCALE, SCALE))
        width, height = pix.width, pix.height
        img = Image.frombytes("RGB", (pix.width, pix.height), pix.samples)
        buf = io.BytesIO()
        img.save(buf, "WEBP", quality=QUALITY, method=6)
        (out / f"p-{i:03d}.webp").write_bytes(buf.getvalue())
    print(f"{key}: {doc.page_count} pages, {width}x{height}")
    return {"pages": doc.page_count, "width": width, "height": height}


def main() -> None:
    meta = {key: render(key, pdf) for key, pdf in BOOKS.items()}
    body = json.dumps(meta, indent=2)
    (ROOT / "src" / "data" / "bookPages.ts").write_text(
        "// Generated by scripts/render-book-pages.py. Do not edit by hand.\n"
        "export type BookKey = \"short\" | \"full\";\n"
        "export type BookPages = { pages: number; width: number; height: number };\n\n"
        f"export const BOOK_PAGES: Record<BookKey, BookPages> = {body};\n\n"
        "export const pageSrc = (book: BookKey, n: number): string =>\n"
        "  `/books/pages/${book}/p-${String(n).padStart(3, \"0\")}.webp`;\n",
        encoding="utf-8",
    )


if __name__ == "__main__":
    main()
