/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CaseStudiesRouteImport } from './routes/case-studies'
import { Route as ClaudeRouteImport } from './routes/claude'
import { Route as CvRouteImport } from './routes/cv'
import { Route as UslugiIndexRouteImport } from './routes/uslugi.index'
import { Route as UslugiSlugRouteImport } from './routes/uslugi.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseStudiesRoute = CaseStudiesRouteImport.update({
  id: '/case-studies',
  path: '/case-studies',
  getParentRoute: () => rootRouteImport,
} as any)
const ClaudeRoute = ClaudeRouteImport.update({
  id: '/claude',
  path: '/claude',
  getParentRoute: () => rootRouteImport,
} as any)
const CvRoute = CvRouteImport.update({
  id: '/cv',
  path: '/cv',
  getParentRoute: () => rootRouteImport,
} as any)
const UslugiIndexRoute = UslugiIndexRouteImport.update({
  id: '/uslugi/',
  path: '/uslugi/',
  getParentRoute: () => rootRouteImport,
} as any)
const UslugiSlugRoute = UslugiSlugRouteImport.update({
  id: '/uslugi/$slug',
  path: '/uslugi/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/case-studies': typeof CaseStudiesRoute
  '/claude': typeof ClaudeRoute
  '/cv': typeof CvRoute
  '/uslugi/$slug': typeof UslugiSlugRoute
  '/uslugi/': typeof UslugiIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/case-studies': typeof CaseStudiesRoute
  '/claude': typeof ClaudeRoute
  '/cv': typeof CvRoute
  '/uslugi/$slug': typeof UslugiSlugRoute
  '/uslugi': typeof UslugiIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/case-studies': typeof CaseStudiesRoute
  '/claude': typeof ClaudeRoute
  '/cv': typeof CvRoute
  '/uslugi/$slug': typeof UslugiSlugRoute
  '/uslugi/': typeof UslugiIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/case-studies'
    | '/claude'
    | '/cv'
    | '/uslugi/$slug'
    | '/uslugi/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/case-studies' | '/claude' | '/cv' | '/uslugi/$slug' | '/uslugi'
  id:
    | '__root__'
    | '/'
    | '/case-studies'
    | '/claude'
    | '/cv'
    | '/uslugi/$slug'
    | '/uslugi/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CaseStudiesRoute: typeof CaseStudiesRoute
  ClaudeRoute: typeof ClaudeRoute
  CvRoute: typeof CvRoute
  UslugiSlugRoute: typeof UslugiSlugRoute
  UslugiIndexRoute: typeof UslugiIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case-studies': {
      id: '/case-studies'
      path: '/case-studies'
      fullPath: '/case-studies'
      preLoaderRoute: typeof CaseStudiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/claude': {
      id: '/claude'
      path: '/claude'
      fullPath: '/claude'
      preLoaderRoute: typeof ClaudeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cv': {
      id: '/cv'
      path: '/cv'
      fullPath: '/cv'
      preLoaderRoute: typeof CvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/uslugi/': {
      id: '/uslugi/'
      path: '/uslugi'
      fullPath: '/uslugi/'
      preLoaderRoute: typeof UslugiIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/uslugi/$slug': {
      id: '/uslugi/$slug'
      path: '/uslugi/$slug'
      fullPath: '/uslugi/$slug'
      preLoaderRoute: typeof UslugiSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CaseStudiesRoute: CaseStudiesRoute,
  ClaudeRoute: ClaudeRoute,
  CvRoute: CvRoute,
  UslugiSlugRoute: UslugiSlugRoute,
  UslugiIndexRoute: UslugiIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
