/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as CaseStudiesRouteImport } from './routes/case-studies'
import { Route as ClaudeRouteImport } from './routes/claude'
import { Route as CvRouteImport } from './routes/cv'
import { Route as KontaktRouteImport } from './routes/kontakt'
import { Route as KsiazkiRouteImport } from './routes/ksiazki'
import { Route as OMnieRouteImport } from './routes/o-mnie'
import { Route as ObszaryIndexRouteImport } from './routes/obszary.index'
import { Route as ObszarySlugRouteImport } from './routes/obszary.$slug'
import { Route as UslugiIndexRouteImport } from './routes/uslugi.index'
import { Route as UslugiSlugRouteImport } from './routes/uslugi.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseStudiesRoute = CaseStudiesRouteImport.update({
  id: '/case-studies',
  path: '/case-studies',
  getParentRoute: () => rootRouteImport,
} as any)
const ClaudeRoute = ClaudeRouteImport.update({
  id: '/claude',
  path: '/claude',
  getParentRoute: () => rootRouteImport,
} as any)
const CvRoute = CvRouteImport.update({
  id: '/cv',
  path: '/cv',
  getParentRoute: () => rootRouteImport,
} as any)
const KontaktRoute = KontaktRouteImport.update({
  id: '/kontakt',
  path: '/kontakt',
  getParentRoute: () => rootRouteImport,
} as any)
const KsiazkiRoute = KsiazkiRouteImport.update({
  id: '/ksiazki',
  path: '/ksiazki',
  getParentRoute: () => rootRouteImport,
} as any)
const OMnieRoute = OMnieRouteImport.update({
  id: '/o-mnie',
  path: '/o-mnie',
  getParentRoute: () => rootRouteImport,
} as any)
const ObszaryIndexRoute = ObszaryIndexRouteImport.update({
  id: '/obszary/',
  path: '/obszary/',
  getParentRoute: () => rootRouteImport,
} as any)
const ObszarySlugRoute = ObszarySlugRouteImport.update({
  id: '/obszary/$slug',
  path: '/obszary/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const UslugiIndexRoute = UslugiIndexRouteImport.update({
  id: '/uslugi/',
  path: '/uslugi/',
  getParentRoute: () => rootRouteImport,
} as any)
const UslugiSlugRoute = UslugiSlugRouteImport.update({
  id: '/uslugi/$slug',
  path: '/uslugi/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/blog': typeof BlogRoute
  '/case-studies': typeof CaseStudiesRoute
  '/claude': typeof ClaudeRoute
  '/cv': typeof CvRoute
  '/kontakt': typeof KontaktRoute
  '/ksiazki': typeof KsiazkiRoute
  '/o-mnie': typeof OMnieRoute
  '/obszary/$slug': typeof ObszarySlugRoute
  '/uslugi/$slug': typeof UslugiSlugRoute
  '/obszary/': typeof ObszaryIndexRoute
  '/uslugi/': typeof UslugiIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/blog': typeof BlogRoute
  '/case-studies': typeof CaseStudiesRoute
  '/claude': typeof ClaudeRoute
  '/cv': typeof CvRoute
  '/kontakt': typeof KontaktRoute
  '/ksiazki': typeof KsiazkiRoute
  '/o-mnie': typeof OMnieRoute
  '/obszary/$slug': typeof ObszarySlugRoute
  '/uslugi/$slug': typeof UslugiSlugRoute
  '/obszary': typeof ObszaryIndexRoute
  '/uslugi': typeof UslugiIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/blog': typeof BlogRoute
  '/case-studies': typeof CaseStudiesRoute
  '/claude': typeof ClaudeRoute
  '/cv': typeof CvRoute
  '/kontakt': typeof KontaktRoute
  '/ksiazki': typeof KsiazkiRoute
  '/o-mnie': typeof OMnieRoute
  '/obszary/$slug': typeof ObszarySlugRoute
  '/uslugi/$slug': typeof UslugiSlugRoute
  '/obszary/': typeof ObszaryIndexRoute
  '/uslugi/': typeof UslugiIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/blog'
    | '/case-studies'
    | '/claude'
    | '/cv'
    | '/kontakt'
    | '/ksiazki'
    | '/o-mnie'
    | '/obszary/$slug'
    | '/uslugi/$slug'
    | '/obszary/'
    | '/uslugi/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/blog'
    | '/case-studies'
    | '/claude'
    | '/cv'
    | '/kontakt'
    | '/ksiazki'
    | '/o-mnie'
    | '/obszary/$slug'
    | '/uslugi/$slug'
    | '/obszary'
    | '/uslugi'
  id:
    | '__root__'
    | '/'
    | '/blog'
    | '/case-studies'
    | '/claude'
    | '/cv'
    | '/kontakt'
    | '/ksiazki'
    | '/o-mnie'
    | '/obszary/$slug'
    | '/uslugi/$slug'
    | '/obszary/'
    | '/uslugi/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BlogRoute: typeof BlogRoute
  CaseStudiesRoute: typeof CaseStudiesRoute
  ClaudeRoute: typeof ClaudeRoute
  CvRoute: typeof CvRoute
  KontaktRoute: typeof KontaktRoute
  KsiazkiRoute: typeof KsiazkiRoute
  OMnieRoute: typeof OMnieRoute
  ObszarySlugRoute: typeof ObszarySlugRoute
  UslugiSlugRoute: typeof UslugiSlugRoute
  ObszaryIndexRoute: typeof ObszaryIndexRoute
  UslugiIndexRoute: typeof UslugiIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case-studies': {
      id: '/case-studies'
      path: '/case-studies'
      fullPath: '/case-studies'
      preLoaderRoute: typeof CaseStudiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/claude': {
      id: '/claude'
      path: '/claude'
      fullPath: '/claude'
      preLoaderRoute: typeof ClaudeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cv': {
      id: '/cv'
      path: '/cv'
      fullPath: '/cv'
      preLoaderRoute: typeof CvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontakt': {
      id: '/kontakt'
      path: '/kontakt'
      fullPath: '/kontakt'
      preLoaderRoute: typeof KontaktRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ksiazki': {
      id: '/ksiazki'
      path: '/ksiazki'
      fullPath: '/ksiazki'
      preLoaderRoute: typeof KsiazkiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/o-mnie': {
      id: '/o-mnie'
      path: '/o-mnie'
      fullPath: '/o-mnie'
      preLoaderRoute: typeof OMnieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/obszary/': {
      id: '/obszary/'
      path: '/obszary'
      fullPath: '/obszary/'
      preLoaderRoute: typeof ObszaryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/obszary/$slug': {
      id: '/obszary/$slug'
      path: '/obszary/$slug'
      fullPath: '/obszary/$slug'
      preLoaderRoute: typeof ObszarySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/uslugi/': {
      id: '/uslugi/'
      path: '/uslugi'
      fullPath: '/uslugi/'
      preLoaderRoute: typeof UslugiIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/uslugi/$slug': {
      id: '/uslugi/$slug'
      path: '/uslugi/$slug'
      fullPath: '/uslugi/$slug'
      preLoaderRoute: typeof UslugiSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BlogRoute: BlogRoute,
  CaseStudiesRoute: CaseStudiesRoute,
  ClaudeRoute: ClaudeRoute,
  CvRoute: CvRoute,
  KontaktRoute: KontaktRoute,
  KsiazkiRoute: KsiazkiRoute,
  OMnieRoute: OMnieRoute,
  ObszarySlugRoute: ObszarySlugRoute,
  UslugiSlugRoute: UslugiSlugRoute,
  ObszaryIndexRoute: ObszaryIndexRoute,
  UslugiIndexRoute: UslugiIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
