// Generated by scripts/render-book-pages.py. Do not edit by hand.
export type BookKey = "short" | "full";
export type BookPages = { pages: number; width: number; height: number };

export const BOOK_PAGES: Record<BookKey, BookPages> = {
  short: {
    pages: 99,
    width: 672,
    height: 953,
  },
  full: {
    pages: 199,
    width: 672,
    height: 953,
  },
};

export const pageSrc = (book: BookKey, n: number): string =>
  `/books/pages/${book}/p-${String(n).padStart(3, "0")}.webp`;
